name: Along with Symfony Deprecations

on: [pull_request, push]

jobs:
    bare_run:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: none

            -   run: composer require symfony/deprecation-contracts

            -   run: php bin/ecs init --ansi --debug
